services:
  evolution-api:
    image: atendai/evolution-api:v1.8.2
    container_name: evolution-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      # Authentication
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=secreta123
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true

      # Server
      - SERVER_URL=http://localhost:8080

      # Configurações gerais
      - DEL_INSTANCE=false
      - CONFIG_SESSION_PHONE_CLIENT=Evolution API
      - CONFIG_SESSION_PHONE_NAME=Chrome

      # Webhook global
      - WEBHOOK_GLOBAL_ENABLED=false

      # QR Code
      - QRCODE_LIMIT=30
      - QRCODE_COLOR=#198754

      # Logging
      - LOG_LEVEL=ERROR
      - LOG_COLOR=true

      # CORS
      - CORS_ORIGIN=*
      - CORS_METHODS=GET,POST,PUT,DELETE
      - CORS_CREDENTIALS=true

    volumes:
      - evolution_instances:/evolution/instances

volumes:
  evolution_instances:
